config/routes.rb
Rails.application.routes.draw do
  get 'authen_accept/accept'
  post 'photos/add-favorite', :to => 'photos#addFavorite'

  resources :galleries 
  get '/o/oauth2/auth', :to => 'authen_accept#accept'
  post 'home/update_gallery', :to => 'home#update_gallery'
  post 'galleries/update', :to => 'galleries#update'
  post 'galleries/add-favorite', :to => 'galleries#addFavorite'
  post 'galleries/add-photo', :to => 'galleries#addPhoto'
  # get 'profile/index'
  get 'profile/events_one', :to => "profile#events_one"
  post 'profile/update', :to => 'profile#update'
  post 'members/update', :to => 'members#update'
  post 'members/update_hours', :to => 'members#update_hours'
  post 'members/delete', :to => 'members#delete'
  post 'home/update', :to => 'home#update'
  get 'members/show', :to => 'members#show'
  resources :news
  resources :posts
 # devise_for :users
  root to: "home#index"
  resources :calendar, only: [:index]
  resources :about, only: [:index]
  resources :home, only: [:index, :update]
  resources :profile, only: [:index, :update]
  resources :members, only: [:index]
  devise_for :users, :controllers => { :registrations => "registrations" }
  #devise_for :users, :controllers => { :registrations => "registrations" }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  resources :photos, only: [:index, :show, :new, :create, :destroy]
  root 'photos#index'
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  # For the sake of testing Heroku
  def index
    @images = Info.first.home_images

    if Info.all.empty?
      @info = Info.new
      @info.save
    else
      @info = Info.first
    end
    @date = Time.now.utc.strftime('%FT%TZ')
    @url = "https://www.googleapis.com/calendar/v3/calendars/americanredcrossatcal@gmail.com/events?key=AIzaSyAN3MLI-jD6mS6425sjj9QcBPWykxvsxZY&timeMin=" + @date
    
    require 'open-uri'
    buffer = open(@url).read
    response = JSON.parse(buffer)
    
    @events = response["items"]
  end
  
  
  def update
    @info = Info.first
    
    if params["bulletin"]
      print("~~~~~" + params["bulletin"].to_s)
      @info.update_bulletin(params["bulletin"])
    end
    
    if params["motm_name"]
      print("~~~~~" + params["motm_name"].to_s)
      @info.update_motm_name(params["motm_name"])
    end
    
    if params["motm_comments"]
      print("~~~~~" + params["motm_comments"].to_s)
      @info.update_motm_comments(params["motm_comments"])
    end
    
    if params[:info][:avatar]
      print("~~~~~~~~~~~~" + params[:info][:avatar].to_s + "~~~~~~~~~")
      @info.update_attribute(:avatar, params[:info][:avatar])
    end
  end

  def update_gallery
    id = params["photo_id"]
    url = params["url"]
    text = params["text"]
    home_image = HomeImage.find(id)
    if url != ""
      home_image.update_attribute(:url, url)
    end
    if text != ""
      home_image.update_attribute(:text, text)
    end
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_loginstat.erb
<% if current_user %>
    <%= link_to('Logout', destroy_user_session_path, :method => :delete) %>
<% elsif %>
    <%= link_to('Login', new_user_session_path, :method => :get) %>
<% end %>

app/views/home/_navbar.erb
<div class="menu-header">
    <div class="logo">
        <a href="/"><img id="navbar-logo" src="/images/logo2.png"></a>
    </div>
    
    <div class="menu">
        <li><%= link_to "Gallery", photos_path, :class => 'home_link' %></li>
        <li><%= link_to "Members", members_path, :class => 'home_link' %></li>
        <li><%= link_to "Calendar", calendar_index_path, :class => 'home_link' %></li>
        <% if current_user %>
            <li><%= link_to 'Logout', destroy_user_session_path, :method => :delete, :class => 'home_link', :id => 'logout_bttn' %></li>
            <li><%= link_to (image_tag(current_user.avatar.url(:thumb), class: 'round-image-50')), profile_index_path %></li>
        <% else %>
<!--             <li class="round-image-50"><%= image_tag("/images/thumb/missing_ava.png") %></li> -->
            <!--<li><%= link_to 'Login', new_user_session_path, :method => :get, :class => 'home_link', :id => 'login_bttn' %></li>-->
            <li class="home_link" id="login_bttn">Login</li>
            <li class="home_link" id="signup_bttn">Sign Up</li>
        <% end %>
        
    </div>
</div>

<div id="home-lightbox-container">
        <div class="screen"></div>
        <div id="login-lightbox">
            <img id="lightbox-logo" src="/images/ARC_Logo_Classic_Horiz_RGB.png">
            <%= form_for(:user, :url => session_path(:user), :html => {id: 'login-form'}) do |f| %>
                <div class="field">
                    <%= f.label :email %>
                    <%= f.email_field :email, autofocus: true %>
                    <img class="login-symbol" src="/images/email.png">
                </div>
                <div class="field">
                    <%= f.label :password %>
                    <%= f.password_field :password, autocomplete: "off" %>
                    <img class="login-symbol" src="/images/password.png">
                </div>
                <% if devise_mapping.rememberable? -%>
                    <div class="field" id="remember-me-home">
                        <%= f.check_box :remember_me %>
                        <%= f.label :remember_me, :id => "remember-me-label" %>
                    </div>
                <% end -%>
                <%= link_to "Forgot your password?", new_password_path(:user), :class => "forgot" %>
                <div class="actions">
                    <a id="signup-bttn">Sign Up</a>
                    <%= f.submit "Log in", :class => "submit" %>
                </div>
                
            <% end %>
            
            <%= form_for(:user, :url => registration_path(:user), :html => {id: 'signup-form'}) do |f| %>
              <%= devise_error_messages! %>
            
              <div class = "name field"> 
                <%= f.label :name %> 
                <%= f.text_field :name, autofocus: true %> 
                <img class="login-symbol" src="/images/name.png">
              </div>
            
              <div class = "major field"> 
                <%= f.label :major %>  
                <%= f.text_field :major, autofocus: true %> 
                <img class="login-symbol" src="/images/major.png">
              </div>
              
              <div class="email field">
                <%= f.label :email %>
                <%= f.email_field :email, autofocus: true %>
                <img class="login-symbol" src="/images/email.png">
              </div>
            
              <div class="field">
                <%= f.label :password %>
                <!--<% if @minimum_password_length %>-->
                <!--<em>(<%= @minimum_password_length %> characters minimum)</em>-->
                <!--<% end %>-->
                <%= f.password_field :password, autocomplete: "off" %>
                <img class="login-symbol" src="/images/password.png">
              </div>
            
              <div class="field">
                <%= f.label :password_confirmation %>
            
                <%= f.password_field :password_confirmation, autocomplete: "off" %>
              </div> 
            
              <div class="actions">
              <a id="signin-bttn">Sign In</a>
                <%= f.submit "Sign up", :class => "submit"%>
              </div>
              
            <% end %>
        </div>
    </div>

<script>
    $('#login_bttn').click(function() {
        console.log("Login clicked");
        $('#home-lightbox-container').show();
    });
    $('#signup_bttn').click(function() {
        console.log("Login clicked");
        $('#home-lightbox-container').show();
        $('#login-form').hide();
        $("#login-lightbox").css("height", "475px")
        $('#signup-form').show();
    });

    $("#login_bttn").mouseenter(function() {
            console.log("HOVERING");
            $(".home-container").css("z-index", "-1")
        }).mouseleave(function() {
            console.log("HOVERING OUT");
            $(".home-container").css("z-index", "1")
        });
    $("#signup_bttn").mouseenter(function() {
            console.log("HOVERING");
            $(".home-container").css("z-index", "-1")
        }).mouseleave(function() {
            console.log("HOVERING OUT");
            $(".home-container").css("z-index", "1")
        });

    $('#signup-bttn').click(function() {
       console.log("Sign Up Clicked");
       $('#login-form').hide();
       $("#login-lightbox").css("height", "475px")
       $('#signup-form').show();
    });
    $('#signin-bttn').click(function() {
       console.log("Sign In Clicked");
       $('#signup-form').hide();
       $("#login-lightbox").css("height", "350px")
       $('#login-form').show();
    });
    $(".screen").click(function() {
        $("#home-lightbox-container").hide();
    });
    
</script>

app/views/home/index.html.erb
<%= render 'navbar' %>
<%= javascript_include_tag('new.js') %>
<div class="home-container">
    <div class="carousel-container">
        <div id="owl-demo" class="home-carousel">
            <% @images.each do |image| %>
                <div class="item crop-height" id=<%= image.id %>>
                    <div class='photo-screen'></div>
                    <div class='photo-text'>
                        <%= image.text %>
                    </div>
                    <% if current_user and current_user.isOfficer %>
                        <div class="edit-home-photo" id=<%= image.id %>>
                            <img class= "edit-home-photo-button" src="images/black_edit.png">
                        </div>
                    <%end%>
                    <div class="edit-home-photo-box">
                        <input type="text" id=<%= image.id %> class="new-photo-url" placeholder="Add your photo url">
                        <label for="new-photo-url">Url</label>
                        <input type="text" id=<%= image.id %> class="new-photo-text" placeholder="Add some text to your photo">
                        <label for="new-photo-url">Text</label>
                        <div id="edit-photo-buttons">
                            <div class="home-cancel">Cancel</div>
                            <div class="home-save">Save</div>
                        </div>
                        
                    </div>
                    <%= image_tag(image.url, :class => "carousel-image") %>
                </div>
            <%end %>
        </div>
    </div>
    
    <div class="home-bottom-section">
        <div class="home-left-section">
            <div class="bulletin-container">
                 <% if current_user and current_user.isOfficer %>
                    <div class="edit-bulletin" id="edit-container">
                        <img src="images/white_edit.png" id="top-edit">
                    </div>
                    <div id="edit-help">
                        Click here to toggle edit content. Editable text will turn red, uneditable text will turn black.
                        <div id="edit-help-carrot"></div>
                    </div>
                <%end%>
                <div class="section-header">
                    <img class="symbol" id="bulletin-symbol" src="/images/bulletin_icon.png"><div class="section-title">BULLETIN</div>
                </div>
                <div class="bulletin-description">
                    <%= @info.bulletin %>
                </div>
            </div>
            <div class="upcoming-events-container">
                <div class="section-header">
                    <img class="symbol" id="events-symbol" src="/images/events_icon.png"><div class="section-title">UPCOMING EVENTS</div>
                </div>
                <div id="upcoming-events">
                    <% if @events.present? %>
                        <% @events.first(4).each do |event| %>
                            <div class="single-event">
                                <%= event["summary"] %><br />
                                <% if event["start"]["date"] %>
                                    <%= Time.parse(event["start"]["date"]).strftime("%B %d, %Y") %>
                                <% else %>
                                    <%= Time.parse(event["start"]["dateTime"]).strftime("%B %d, %Y") %>
                                <% end %>
                            </div>
                        <% end %>
                    <% else %>
                        No Event Available
                    <% end %>
                </div>
            </div>
        </div>
        
        <div class="home-right-section">
            <div class="member-of-month-container">
                <% if current_user and current_user.isOfficer %>
                    <div class="edit-motm" id="edit-container">
                        <img src="images/white_edit.png" id="top-edit">
                    </div>
                    <div id="edit-help">
                        Click here to toggle edit content. Editable text will turn red, uneditable text will turn black.
                        <div id="edit-help-carrot"></div>
                    </div>
                <%end%>
                <div class="section-header">
                    <img class="symbol" id="mom-symbol" src="/images/member_of_the_month_icon.png"><div class="section-title">MEMBER OF THE MONTH</div>
                </div>
                <div class="motm-avatar">
                    <%= image_tag(@info.avatar.url(:medium), :class => "motm-image") %>
                    <% if current_user and current_user.isOfficer %>
                        <%= form_for @info, :url => {:action => :update}, :html => { :multipart => true } do |form| %>
                            <%= form.file_field :avatar %>
                            <%= form.submit "upload" %>
                        <% end %>
                        <label for="info_avatar" id="edit-motm-photo">Edit Photo</label>
                    <%end%>
                </div>
                
                <div class="motm-name">
                    <%=@info.name %>
                </div>
                <div class="motm-comments">
                    <%= @info.comments %>
                </div>
            </div>
        </div>
        
    </div>
    
    <div class="home-footer-container">
        <div class="home-footer">
            <img class="copyright-symbol" src="images/copyright-symbol.png"><p>2016 Cal Red Cross Association</p>
        </div>
    </div>
</div>

<script>
    var current_photo;
    $(".home-carousel").slick({
        arrows: true,
        dots: true,
        infinite: true,
        speed: 500,
        fade: true,
        cssEase: 'linear'
    });
    
    $(".edit-bulletin").click(function() {
        console.log("EDIT bulletin");
        $(this).toggleClass("home-active");
        if (!$(this).hasClass("home-active")) {
            $.ajax({
                type : 'post',
                url : "/home/update",
                data : {"bulletin": $(".bulletin-description").text()},    
                dataType : 'json',
                async : false,
                context : document.body,
                success : function(response) {
                }
            });
        }
        var $div=$('.bulletin-description'), isEditable=$div.is('.editable');
        $div.prop('contenteditable',!isEditable).toggleClass('editable')
        $div.toggleClass("home-active");
    });
    $(".edit-motm").click(function() {
        console.log("EDIT Member Of The Month");
        $(this).toggleClass("home-active");
        if (!$(this).hasClass("home-active")) {
            $.ajax({
                type : 'post',
                url : "/home/update",
                data : {"motm_name": $(".motm-name").text(),
                        "motm_comments": $(".motm-comments").text()
                },    
                dataType : 'json',
                async : false,
                context : document.body,
                success : function(response) {
                }
            });
        }
        var $div=$('.motm-name'), isEditable=$div.is('.editable');
        $div.prop('contenteditable',!isEditable).toggleClass('editable')
        $div.toggleClass("home-active");
        
        var $div=$('.motm-comments'), isEditable=$div.is('.editable');
        $div.prop('contenteditable',!isEditable).toggleClass('editable')
        $div.toggleClass("home-active");
    });
    $('#info_avatar').change(function(e) {
                    var img = URL.createObjectURL(e.target.files[0]);
                    $(".motm-image").attr("src", img);
                    $(".edit_info").submit();
                });
    $(".edit-home-photo").click(function() {
        $(".edit-home-photo-box").toggle();
        current_photo = $(this).attr("id");
        console.log("Clicked " + current_photo);
    });
    $(".home-cancel").click(function() {
        $(".edit-home-photo-box").toggle();
    });
    $(".home-save").click(function() {
        $(".edit-home-photo-box").toggle();
        var url = $("#" + current_photo + ".new-photo-url").val();
        var text = $("#" + current_photo + ".new-photo-text").val();
        console.log(url);
        console.log(text);
        $.ajax({
            type : 'post',
            url : "/home/update_gallery",
            data : {"url": url,
                    "text": text,
                    "photo_id": current_photo
            },    
            dataType : 'json',
            async : false,
            context : document.body,
            success : function(response) {
                $("#" + current_photo + " .carousel-image").attr("src", url);
                $("#" + current_photo + " .photo-text").text(text);
            }
        });
    });

</script>