config/routes.rb
Rails.application.routes.draw do
  get 'authen_accept/accept'
  post 'photos/add-favorite', :to => 'photos#addFavorite'

  resources :galleries 
  get '/o/oauth2/auth', :to => 'authen_accept#accept'
  post 'home/update_gallery', :to => 'home#update_gallery'
  post 'galleries/update', :to => 'galleries#update'
  post 'galleries/add-favorite', :to => 'galleries#addFavorite'
  post 'galleries/add-photo', :to => 'galleries#addPhoto'
  # get 'profile/index'
  get 'profile/events_one', :to => "profile#events_one"
  post 'profile/update', :to => 'profile#update'
  post 'members/update', :to => 'members#update'
  post 'members/update_hours', :to => 'members#update_hours'
  post 'members/delete', :to => 'members#delete'
  post 'home/update', :to => 'home#update'
  get 'members/show', :to => 'members#show'
  resources :news
  resources :posts
 # devise_for :users
  root to: "home#index"
  resources :calendar, only: [:index]
  resources :about, only: [:index]
  resources :home, only: [:index, :update]
  resources :profile, only: [:index, :update]
  resources :members, only: [:index]
  devise_for :users, :controllers => { :registrations => "registrations" }
  #devise_for :users, :controllers => { :registrations => "registrations" }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  resources :photos, only: [:index, :show, :new, :create, :destroy]
  root 'photos#index'
end

app/models/news.rb
class News < ApplicationRecord
end

app/helpers/news_helper.rb
module NewsHelper
end

app/views/news/_form.html.erb
<%= form_for(news) do |f| %>
  <% if news.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(news.errors.count, "error") %> prohibited this news from being saved:</h2>

      <ul>
      <% news.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div class="field">
    <%= f.label :content %>
    <%= f.text_field :content %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/news/_loginstat.erb
<% if current_user %>
    <%= link_to('Logout', destroy_user_session_path, :method => :delete) %>
<% elsif %>
    <%= link_to('Login', new_user_session_path, :method => :get) %>
<% end %>

app/views/news/edit.html.erb
<%= render 'loginstat' %>

<h1>Editing News</h1>

<%= render 'form', news: @news %>

<%= link_to 'Show', @news %> |
<%= link_to 'Back', news_index_path %>

app/views/news/index.html.erb
<%= render 'loginstat' %>

<p id="notice"><%= notice %></p>

<h1>News</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Content</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @news.each do |news| %>
      <tr>
        <td><%= news.title %></td>
        <td><%= news.content %></td>
        <td><%= link_to 'Show', news %></td>
        <td><%= link_to 'Edit', edit_news_path(news) %></td>
        <td><%= link_to 'Destroy', news, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New News', new_news_path %>

app/views/news/new.html.erb
<%= render 'loginstat' %>
    
<h1>New News</h1>

<%= render 'form', news: @news %>

<%= link_to 'Back', news_index_path %>

app/views/news/show.html.erb
<%= render 'loginstat' %>
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @news.title %>
</p>

<p>
  <strong>Content:</strong>
  <%= @news.content %>
</p>

<%= link_to 'Edit', edit_news_path(@news) %> |
<%= link_to 'Back', news_index_path %>